description: |
  ### Document Name - SHARR_Remediation_AFSBP_EC2.2

  ## What does this document do?
  This document deleted ingress and egress rules from default security group

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.

  ## Output Parameters
  * Remediation.Output - Output from AWSConfigRemediation-RemoveVPCDefaultSecurityGroupRules SSM doc
schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
outputs:
  - Remediation.Output
  - ParseInput.AffectedObject
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: '^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/[\w+=,.@-]+'
  Finding:
    type: StringMap
    description: The input from Step function for EC2.2 finding
mainSteps:
  - name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: GroupId
        Selector: $.Payload.group_id
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
      Runtime: python3.6
      Handler: parse_event
      Script: |-
        def parse_event(event, context):
          finding = event['Finding']
          finding_id = finding['Id']
          product_arn = finding['ProductArn']
          group_id = finding['Resources'][0]['Details']['AwsEc2SecurityGroup']['GroupId']
          object = {'Type': 'SecurityGroup', 'Id': group_id, 'OutputKey': 'Remediation.Output'}
          return {"group_id": group_id, "finding_id": finding_id, "product_arn": product_arn, "object": object}
    isEnd: false
  - name: Remediation
    action: 'aws:executeAutomation'
    isEnd: false
    inputs:
      DocumentName: AWSConfigRemediation-RemoveVPCDefaultSecurityGroupRules
      RuntimeParameters:
        GroupId: '{{ ParseInput.GroupId }}'
        AutomationAssumeRole: '{{ AutomationAssumeRole }}'
  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
        - Id: '{{ParseInput.FindingId}}'
          ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: Removed rules on default security group
        UpdatedBy: SHARR_Remediation_AFSBP_EC2.2
    description: Update finding
    isEnd: true
