description: |
  ### Document Name - SHARR_Remediation_AFSBP_RDS.7

  ## What does this document do?
  This document enables `Deletion Protection` on a given Amazon RDS cluster by calling another SSM document.

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.

  ## Output Parameters
  * Remediation.Output - The standard HTTP response from the ModifyDBInstance API.
schemaVersion: "0.3"
assumeRole: "{{ AutomationAssumeRole }}"
parameters:
  AutomationAssumeRole:
    type: String
    description: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
    allowedPattern: ^arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/[\w+=,.@-]+
  Finding:
    type: StringMap
    description: The input from Step function for RDS7 finding
outputs:
  - Remediation.Output
  - ParseInput.AffectedObject
mainSteps:
  -
    name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: ResourceId
        Selector: $.Payload.resource_id
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
      Runtime: python3.6
      Handler: parse_event
      Script: |-
        def parse_event(event, context):
          finding = event['Finding']
          finding_id = finding['Id']
          product_arn = finding['ProductArn']
          resource_id = finding['Resources'][0]['Details']['AwsRdsDbCluster']['DbClusterResourceId']
          object = {'Type': 'RDSCluster', 'Id': resource_id, 'OutputKey': 'Remediation.Output'}
          return {"resource_id": resource_id, "finding_id": finding_id, "product_arn": product_arn, "object": object}
    isEnd: false
  -
    name: Remediation
    action: 'aws:executeAutomation'
    isEnd: false
    inputs:
      DocumentName: AWSConfigRemediation-EnableRDSClusterDeletionProtection
      RuntimeParameters:
        ClusterId: '{{ ParseInput.ResourceId }}'
        AutomationAssumeRole: '{{ AutomationAssumeRole }}'
  - 
    name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Deletion protection enabled on RDS DB cluster'
        UpdatedBy: 'SHARR_Remediation_AFSBP_RDS.7'
    description: Update finding
    isEnd: true
